{
 "title": "GraphQL",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Server request pr second (5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name)(rate(http_server_requests_seconds_count{io_kompose_service=\"graphql\",uri=\"root\",method=\"POST\"}[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Client requests pr second (5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (rate(http_client_requests_seconds_count{io_kompose_service=\"graphql\",method=\"GET\",clientName=\"api.felleskomponent.no\"}[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Duration (5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{status!~\"5..\"}[15m])) / sum(rate(http_client_requests_seconds_count{status!~\"5..\"}[5m]))",
     "legendFormat": "AVG Client"
    },
    {
     "expr": "max(http_server_requests_seconds_max{io_kompose_service=\"graphql\", status!~\"5..\"})",
     "legendFormat": "MAX Server"
    },
    {
     "expr": "max(http_client_requests_seconds_max{io_kompose_service=\"graphql\", status!~\"5..\"})",
     "legendFormat": "MAX Client"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\"}[5m])) / sum(rate(http_server_requests_seconds_count{status!~\"5..\"}[5m]))",
     "legendFormat": "AVG Server"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{io_kompose_service=\"graphql\",uri=\"root\", method=\"POST\"})",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{io_kompose_service=\"graphql\",uri=\"root\", method=\"POST\", status=~\"5..\"})",
     "legendFormat": "Total Server Errors"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{io_kompose_service=\"graphql\",uri=\"root\", method=\"POST\", status=~\"4..\"})",
     "legendFormat": "Total Client Errors"
    }
   ]
  },
  {
   "title": "Client side 4xx's (5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (\n  rate(http_client_requests_seconds_count{io_kompose_service=\"graphql\", method=\"GET\", status=~\"4..\"}[5m])\n)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Server side 5xx's (5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (\n  rate(http_server_requests_seconds_count{io_kompose_service=\"graphql\", method=\"POST\", status=~\"5..\"}[5m])\n)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}