{
 "title": "Kundeportal",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errors (5xx)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(uri, exception, status) (http_server_requests_seconds_count{io_kompose_service=\"kunde-portal\", status=~\"5..\", uri=~\"/api.*\", exception!=\"None\"})",
     "legendFormat": "{{uri}} - 5xx"
    }
   ]
  },
  {
   "title": "Errors (4xx)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(uri, exception, status) (http_server_requests_seconds_count{io_kompose_service=\"kunde-portal\", status=~\"4..\", uri=~\"/api.*\", exception!=\"None\"})",
     "legendFormat": "{{uri}} - 4xx"
    }
   ]
  },
  {
   "title": "Successful by URIs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (uri, method, status) (rate(http_server_requests_seconds_count{io_kompose_service=\"kunde-portal\", method=~\"GET|POST|PUT|DELETE\", uri=~\"/api.*\", status=~\"2..|3..\"}[5m]))",
     "legendFormat": "{{method}} - {{uri}} ({{status}})"
    }
   ]
  }
 ]
}