{
 "title": "NAM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg network pr day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{host=~\"namagw01|namagw02\", device=\"eth0\"}[1d])",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{host=~\"namagw01|namagw02\", device=\"eth0\"}[1d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network Traffic (5m) on eth0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes", "label": "bytes in (-) / bytes out (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{service=\"nam\",device=\"eth0\"}[5m])",
     "legendFormat": "{{host}}_in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{service=\"nam\",device=\"eth0\"}[5m])",
     "legendFormat": "{{host}}_out"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Used disk space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", service=\"nam\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", service=\"nam\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Used disk space (Alert)",
   "type": "graph",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", service=\"nam\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", service=\"nam\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Memory and CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(host)(rate(node_cpu_seconds_total{mode=\"idle\",service=\"nam\"}[5m]) *100))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(host) (node_cpu_seconds_total{service=\"nam\", mode=\"system\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{service=\"nam\"} - node_memory_MemFree_bytes{service=\"nam\"}) / 1024 / 1024 / 1024",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}